export const START_SESSION_SUCCESS='START_SESSION_SUCCESS';
export const START_SESSION_FAILED='START_SESSION_FAILED';


export const DELETE_SESSION_SUCCESS='DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_FAILURE='DELETE_SESSION_FAILURE';

export const CHANGE_SESSION_FAILURE_NUM_SUCCESS='CHANGE_SESSION_FAILURE_NUM_SUCCESS';
export const CHANGE_SESSION_FAILURE_NUM_FAILURE='CHANGE_SESSION_FAILURE_NUM_FAILURE';