export const START_SESSION_SUCCESS='START_SESSION_SUCCESS';
export const START_SESSION_FAILED='START_SESSION_FAILED';

export const DELETE_SESSION_SUCCESS='DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_FAILURE='DELETE_SESSION_FAILURE';

export const CHANGE_SESSION_FAILURE_NUM_SUCCESS='CHANGE_SESSION_FAILURE_NUM_SUCCESS';
export const CHANGE_SESSION_FAILURE_NUM_FAILURE='CHANGE_SESSION_FAILURE_NUM_FAILURE';

export const SET_FAILURE_RATE_NUMBER='SET_FAILURE_RATE_NUMBER';

export const GET_ALL_TODOS_SUCCESS='GET_ALL_TODOS_SUCCESS';
export const GET_ALL_TODOS_FAILED='GET_ALL_TODOS_FAILED';

export const ALTER_TODO_IN_STATE_SUCCESS='ALTER_TODO_IN_STATE_SUCCESS';
export const ALTER_TODO_IN_STATE_FAILED='ALTER_TODO_IN_STATE_FAILED';

export const DELETE_TODO_SUCCESS='DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILED='DELETE_TODO_FAILED';