export const enum SessionActionTypes{
    START_SESSION_SUCCESS='@@session/START_SESSION_SUCCESS',
    START_SESSION_FAILED='@@session/START_SESSION_FAILED',
    DELETE_SESSION_SUCCESS='@@session/DELETE_SESSION_SUCCESS',
    DELETE_SESSION_FAILURE='@@session/DELETE_SESSION_FAILURE',
    CHANGE_SESSION_FAILURE_NUM_SUCCESS='@@session/CHANGE_SESSION_FAILURE_NUM_SUCCESS',
    CHANGE_SESSION_FAILURE_NUM_FAILURE='@@session/CHANGE_SESSION_FAILURE_NUM_FAILURE',
    SET_FAILURE_RATE_NUMBER='@@session/SET_FAILURE_RATE_NUMBER'
}

export interface SessionState{
    readonly sessionId:string,
    readonly failure:number
}